# Generated by Django 6.0.3 on 2026-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyguide",
            name="difficulty_rating",
            field=models.IntegerField(default=1),
        ),
    ]
