# Generated by Django 6.0.3 on 2026-03-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0003_subject_subtopic_topic_delete_studyguide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
