# Generated by Django 6.0.3 on 2026-03-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0004_alter_subject_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="subject",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
