# Generated by Django 6.0.3 on 2026-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processor", "0005_remove_topic_subject_delete_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtopic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
